### ISSUE TITLE
Label Sync Issue

### ISSUE THREAD

**Issue by kentlangley** [exoeconomy/EXOS-Electrum#20]
I cannot get labels to sync to wallet.

The wallet is from a previous CIVX wallet (electrum) that moved to (EXOS) by restoring on a diff. computer to latest EXOS version.

I still get label syncs on my old wallet (which I do still have)

I do not get label syncs on the new EXOS version of the same wallet no matter what I do.

Can't see that its anything I'm doing. So, ideas welcome.

**Comment by turcol** [comment]
You can install the EXOS-Electrum wallet in the same computer where you have your CIVX wallet before you migrate it to a new computer.

With both wallets closed (EXOS and CIVX), copy the wallet file from the CIVX wallet that you would like to migrate to the new computer, to the EXOS wallet's directory you just installed. Assuming the CIVX wallet's name is wallet1 (and the wallet is on its default directory), the commands from the terminal/console would be like this:
```
cp  ~/.electrum-civx/wallets/wallet1 ~/exos-electrum/wallets/
```
Now, open your EXOS-Electrum wallet, and this time  sync the labels. Once you have synced them, you can just use your seed phrase in your new computer to reestablish your wallet and do sync your labels in your new computer.

We have migrated the labels and cosigner servers used with CIVX (from the upstream) after we migrated from CIVX to EXOS, and now we are using the OpenExO servers.

**Comment by kentlangley** [comment]
yes but Michelle is on Electrum EXOS. She has the labels locally. I migrated from CIVX to EXOS by restoring from Seed on a new computer. I asked her to upload the labels again for me and then I tried to download them. Why would her upload not actually upload the labels the new servers?
